package net.level3studios.arithmetick.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006590)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFc6e7ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001e2f)
val md_theme_light_secondary = Color(0xFF5e6300)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFe3ea74)
val md_theme_light_onSecondaryContainer = Color(0xFF1b1d00)
val md_theme_light_tertiary = Color(0xFF006c4c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF88f8c9)
val md_theme_light_onTertiaryContainer = Color(0xFF002114)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inversePrimary = Color(0xFF82cfff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF82cfff)
val md_theme_dark_onPrimary = Color(0xFF00344d)
val md_theme_dark_primaryContainer = Color(0xFF004c6e)
val md_theme_dark_onPrimaryContainer = Color(0xFFc6e7ff)
val md_theme_dark_secondary = Color(0xFFc6cd5b)
val md_theme_dark_onSecondary = Color(0xFF2f3300)
val md_theme_dark_secondaryContainer = Color(0xFF454a00)
val md_theme_dark_onSecondaryContainer = Color(0xFFe3ea74)
val md_theme_dark_tertiary = Color(0xFF6adbad)
val md_theme_dark_onTertiary = Color(0xFF003825)
val md_theme_dark_tertiaryContainer = Color(0xFF005138)
val md_theme_dark_onTertiaryContainer = Color(0xFF88f8c9)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_inverseOnSurface = Color(0xFF1C1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inversePrimary = Color(0xFF006590)
val md_theme_dark_shadow = Color(0xFF000000)



val seed = Color(0xFF6750A4)
val error = Color(0xFFB3261E)
val CustomPurple = Color(0xFF805d93)
val CustomPink = Color(0xFFf49fbc)
val CustomGreen = Color(0xFF169873)
val CustomBlue = Color(0xFF2f3061)
val CustomOrange = Color(0xFFff7f11)
val CustomRed = Color(0xFFd7263d)